name: CI

on:
  push:
    branches: [ "main", "sylvain", "phily", "ethan", "virgile" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "23"
          cache: maven

      - name: Install LML dependencies
        run: |
          cd libs
          mvn clean install -DskipTests -N
          cd libLML
          mvn clean install -DskipTests
          cd ../..

      - name: Build (Maven Wrapper)
        run: |
          chmod +x mvnw
          ./mvnw -B -U -DskipTests clean package
